name: unitype
description: A smart image board.
version: 0.1.0

environment:
  sdk: ">=2.3.0"

dependencies:
  test: any
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ">=1.3.0 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui